---
- name: Ensure target directory exists
  ansible.builtin.file:
    path: /opt/ansible-managed
    state: directory
    mode: "0755"

- name: Create Jinja2 template for IP commands
  ansible.builtin.template:
    src: rootfs/opt/ansible-managed/ip-command.sh.j2
    dest: /opt/ansible-managed/ip-command.sh
    mode: "0755"

- name: Add IP commands script to cron on boot
  ansible.builtin.cron:
    name: "Run IP commands script on boot"
    special_time: reboot
    job: "/opt/ansible-managed/ip-commands.sh"
