- name: Reboot all hosts
  hosts: ifog
  become: true
  tasks:
    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 900 # 15 minutes

- name: Reboot all hosts
  hosts: purevoltage
  become: true
  tasks:
    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 900 # 15 minutes
