- name: Get cloud images from url
  ansible.builtin.include_tasks: name-url.yml
  when: item.url is defined and item.name is not defined

- name: Get cloud images
  ansible.builtin.include_tasks: name-img.yml
  when: item.url is defined and item.name is defined
