---
# confirm that the bird package is installed
- name: Ensure bird is installed
  ansible.builtin.command: bird --version
  register: bird_version
  changed_when: bird_version.rc != 0
  ignore_errors: true

- name: Install bird
  ansible.builtin.import_tasks:
    file: compile-bird/main.yml
  when: bird_update or bird_version.rc != 0

- name: Ensure bird group exist
  ansible.builtin.group:
    name: bird
    state: present

- name: Ensure bird user exists
  ansible.builtin.user:
    name: bird
    group: bird
    state: present
    createhome: false
    system: true
    shell: /usr/sbin/nologin

- name: Ensure /usr/lib/bird exist
  ansible.builtin.file:
    path: /usr/lib/bird
    state: directory
    mode: "0755"

- name: Ensure prepare-environment script is present
  ansible.builtin.copy:
    src: rootfs/usr/lib/bird/prepare-environment
    dest: /usr/lib/bird/prepare-environment
    mode: "0755"

- name: Copy systemd service file
  ansible.builtin.copy:
    src: rootfs/lib/systemd/system/bird.service
    dest: /lib/systemd/system/bird.service
    mode: "0644"

- name: Ensure bird directory exists
  ansible.builtin.file:
    path: /etc/bird
    # path: /root/test/
    state: directory
    owner: bird
    mode: "0755"

- name: Ensure bird is enabled
  ansible.builtin.systemd:
    name: bird
    enabled: "{{ bird_enabled }}"

- name: Ensure authorized_bird_users are added to bird group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: bird
    append: true
  loop: "{{ authorized_bird_users }}"

- name: Import template tasks
  ansible.builtin.import_tasks:
    file: templates.yml

- name: Check if bird is running
  ansible.builtin.systemd:
    name: bird
    state: "{{ bird_state }}"
