---

- name: Create the directory for Loki
  ansible.builtin.file:
    path: /opt/docker-compose/loki
    recurse: true
    state: directory
    mode: '0755'

- name: Get docker compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/grafana/loki/v3.0.0/production/docker-compose.yaml
    dest: /opt/docker-compose/loki/docker-compose.yaml
    mode: '0644'

- name: Create docker-compose service
  ansible.builtin.template:
    src: docker-compose.service.j2
    dest: /etc/systemd/system/loki.service
    mode: '0644'

- name: Start Loki
  ansible.builtin.systemd:
    name: loki
    enabled: true
    state: started
    daemon_reload: true
    no_block: true
