# roles/common/tasks/main.yml
- name: Explaning the environment
  ansible.builtin.debug:
    msg: "The deployment is {{ deployment }}"
  when: inventory_hostname in groups['all']

- name: Run linux Tasks
  ansible.builtin.import_tasks: linux/main.yml
  become: true
  when: (ansible_facts['os_family'] != 'FreeBSD' and ansible_facts['os_family'] != 'Windows')
