- name: Clean up directory
  ansible.builtin.file:
    path: /root/cloud-images
    state: absent
  when: cleanup_cloud_images

- name: Confirm cloud-images directory exists
  ansible.builtin.file:
    path: /root/cloud-images
    state: directory
    mode: "0755"

- name: Get cloud images
  ansible.builtin.include_tasks: get/main.yml
  loop: "{{ cloud_images }}"
